In [1]:
# 이 챕터는 다시 설명

In [2]:
import cv2

In [3]:
!pip install opencv-python

In [4]:
!pip uninstall opencv-python

Found existing installation: opencv-python 4.3.0.36
Uninstalling opencv-python-4.3.0.36:
  Would remove:
    /home/bitai/.local/lib/python3.7/site-packages/cv2/*
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python-4.3.0.36.dist-info/*
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libQtCore-6b7bca35.so.4.8.7
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libQtGui-a00f4bbc.so.4.8.7
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libQtTest-6d3ddc1c.so.4.8.7
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libXcursor-1a09904e.so.1.0.2
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libXfixes-d274cb03.so.3.1.0
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libXi-e28fba09.so.6.1.0
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.libs/libXinerama-b7a62e01.so.1.0.0
    /home/bitai/.local/lib/python3.7/site-packages/opencv_python.lib

In [5]:
print(cv2.__version__)

4.3.0


In [6]:
import numpy as np

In [7]:
img = np.random.randint(0, 10, (7, 7))
print(img)

[[9 6 5 6 8 5 0]
 [8 0 2 7 0 9 0]
 [3 8 6 3 8 0 6]
 [6 0 8 7 5 1 3]
 [6 5 3 3 5 5 8]
 [4 6 0 0 7 5 3]
 [1 1 6 8 3 2 1]]


In [8]:
img_np= np.ones([7,7])

print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [9]:
kernel = np.array([-1, 0, 1])
print(kernel)

[-1  0  1]


In [10]:
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
img_cv = cv2.resize(img_np,(7,7))
print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [12]:
kernel = cv2.resize(kernel, (1, 3))

print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [13]:
print(type(img_cv))
print(type(kernel))
# 편하게 이미지 연산할 수 있게함

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
conv_test = cv2. filter2D(img_cv, -1, kernel)

print(conv_test)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [15]:
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [16]:
print(img_cv)
# 0의 자리를 계산하려고 할 때
# 먼저 그 뒤의 1을

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

# filter2D - Con
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [18]:
# p262 
# convolution WIKI 검색
# 라플라스 트랜스폼 : 0 부터 무한대 까지 적분하는데, f(x) 에  e^ 한 것
# 라플라스 트랜스폼은 0부터 무한대 까지 적분해서 구간만 바뀌고 개념 비슷 s 도메인
# 프리에트렌스폼 : 일반 도매인
# 컨벌루션할 때 위 2이 중요한 이유 
# filter2D가 하는 일: 걸러내는 일
# 컨벌루션하면 왜 걸러질까?
# 프리에트랜스폼 : 스펙트럼분석을 한다는 것 -> 주파수가 나온다는 것 -> 신호파형이라면 해당주파수의 신호보여줌
# 프리에트랜스폼과 컨벌루션이 관계를 가짐 
# 라플라스 : 필터자체를 설계
# 필터링하면서 컨벌루션

In [19]:
# 라플라스 변환 => 전달 함수를 얻기 위해 계산함
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출력이 7, 입출력비: 7/10
# 입력이 y'' = y' + 3y + 2
# 출력이 y' = 3e^3x => y = e^3x
# 라플라스 변환 통해 입출력비를 계산할 수 있게 된다.
# integral 0 ~ inf f(t)e^-st dt

# Low Pass Filter(LPF 설계법) - 1D Convolution
# 전달함수 -> 실제 값을 필터링 하는 방법

In [20]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [21]:
classifier = Sequential()
classifier.add(
    Conv2D(
        32, (3, 3), 
        input_shape = (64, 64, 3), 
        activation = 'relu'
    )
)
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())

In [22]:
# 텐서연산
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(64, activation = 'relu')
)
classifier.add(
    Dense(32, activation = 'relu')
)
classifier.add(
    Dense(16, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'sigmoid')
)

classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [23]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 30752)             0         
_________________________________________________________________
dense (Dense)                (None, 128)               3936384   
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 128)               1

In [24]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale = 1.0 / 255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

train_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [25]:
# 테스트 데이터 만들기

In [26]:
!ls Applied-Deep-Learning-with-Keras

Lesson01  Lesson03  Lesson05  Lesson07	Lesson09  README.md
Lesson02  Lesson04  Lesson06  Lesson08	LICENSE


In [27]:
!ls Applied-Deep-Learning-with-Keras/Lesson07

Activity13.ipynb  Datasets	    Exercise20.ipynb  Exercise22.ipynb
Activity14.ipynb  Exercise19.ipynb  Exercise21.ipynb


In [28]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset

test_set  training_set


In [29]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set


cats  dogs


In [30]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set

cats  dogs


In [31]:
# 64로 맞추는 이유 : 네트워크, 이미지를 64로 맞췄기 때문
trainSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/training_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)
testSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/test_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [32]:
# fitting -> 컨벌루션(라플라스 푸리에를 고려할 수 있는 형태로)
batch_size = 100

classifier.fit_generator(
    trainSet,
    steps_per_epoch = int(10000/batch_size),
    epochs = 100,
    validation_data = testSet,
    validation_steps = int(2500/batch_size)
)

Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/100
 53/100 [==============>...............] - ETA: 2s - loss: 0.7012 - accuracy: 0.4988

/home/bitai/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data.  Expecting to read 32 bytes but only got 0. Skipping tag 270
  " Skipping tag %s" % (size, len(data), tag)
/home/bitai/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data.  Expecting to read 5 bytes but only got 0. Skipping tag 271
  " Skipping tag %s" % (size, len(data), tag)
/home/bitai/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 272
  " Skipping tag %s" % (size, len(data), tag)
/home/bitai/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 282
  " Skipping tag %s" % (size, len(data), tag)
/home/bitai/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly

100/100 [==============================] - 8s 80ms/step - loss: 0.6880 - accuracy: 0.5372 - val_loss: 0.6850 - val_accuracy: 0.5537
Epoch 2/100
100/100 [==============================] - 8s 77ms/step - loss: 0.6472 - accuracy: 0.6206 - val_loss: 0.6005 - val_accuracy: 0.6775
Epoch 3/100
100/100 [==============================] - 8s 76ms/step - loss: 0.5853 - accuracy: 0.6850 - val_loss: 0.5979 - val_accuracy: 0.6812
Epoch 4/100
100/100 [==============================] - 8s 77ms/step - loss: 0.5591 - accuracy: 0.7212 - val_loss: 0.5821 - val_accuracy: 0.6900
Epoch 5/100
100/100 [==============================] - 8s 77ms/step - loss: 0.5467 - accuracy: 0.7166 - val_loss: 0.5954 - val_accuracy: 0.7225
Epoch 6/100
100/100 [==============================] - 8s 77ms/step - loss: 0.5199 - accuracy: 0.7403 - val_loss: 0.5625 - val_accuracy: 0.7287
Epoch 7/100
100/100 [==============================] - 8s 77ms/step - loss: 0.5068 - accuracy: 0.7656 - val_loss: 0.5721 - val_accuracy: 0.7225
Epoc

100/100 [==============================] - 8s 78ms/step - loss: 0.0341 - accuracy: 0.9887 - val_loss: 1.4290 - val_accuracy: 0.7312
Epoch 58/100
100/100 [==============================] - 8s 77ms/step - loss: 0.0423 - accuracy: 0.9869 - val_loss: 1.2494 - val_accuracy: 0.7200
Epoch 59/100
100/100 [==============================] - 8s 77ms/step - loss: 0.0322 - accuracy: 0.9862 - val_loss: 1.2214 - val_accuracy: 0.7487
Epoch 60/100
100/100 [==============================] - 8s 76ms/step - loss: 0.0334 - accuracy: 0.9891 - val_loss: 1.0972 - val_accuracy: 0.7287
Epoch 61/100
100/100 [==============================] - 8s 76ms/step - loss: 0.0295 - accuracy: 0.9894 - val_loss: 2.0163 - val_accuracy: 0.7425
Epoch 62/100
100/100 [==============================] - 8s 77ms/step - loss: 0.0417 - accuracy: 0.9869 - val_loss: 0.8718 - val_accuracy: 0.7575
Epoch 63/100
100/100 [==============================] - 8s 78ms/step - loss: 0.0376 - accuracy: 0.9866 - val_loss: 1.6419 - val_accuracy: 0.711

In [33]:
# p261

In [34]:
import numpy as np

from keras.preprocessing import image

In [35]:
new_image = image.load_img(
    'test_image_2.jpg',
    target_size = (64, 64)
)

In [36]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

result = classifier.predict(new_image)
#trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

Cat


In [ ]:
# Convolution이 너무 많으면 특징을 더 복잡하게 잡아서
# 결과가 안좋게 나올 수 있음 